apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aws-backend
  template:
    metadata:
      labels:
        app: aws-backend
    spec:
      containers:
      - name: aws-backend
        image: udaykiranchilumula/aws-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: postgres-writer
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: aws-backend
spec:
  selector:
    app: aws-backend
  ports:
    - port: 5000
      targetPort: 5000
