apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-backend
  template:
    metadata:
      labels:
        app: aws-backend
    spec:
      containers:
      - name: aws-backend
        image: udaykiranchilumula/aws-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: HOST
          value: postgres
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: aws-backend
spec:
  selector:
    app: aws-backend
  ports:
    - port: 5000
      targetPort: 5000
