apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS ec2_instances (
        id SERIAL PRIMARY KEY,
        instance_id VARCHAR(50) NOT NULL,
        instance_type VARCHAR(50),
        state VARCHAR(30),
        private_ip VARCHAR(50),
        public_ip VARCHAR(50),
        launch_time TIMESTAMP,
        region VARCHAR(30),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS s3_buckets (
        id SERIAL PRIMARY KEY,
        bucket_name VARCHAR(255) NOT NULL,
        creation_date TIMESTAMP,
        region VARCHAR(30),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS rds_instances (
        id SERIAL PRIMARY KEY,
        db_instance_identifier VARCHAR(100) NOT NULL,
        engine VARCHAR(50),
        status VARCHAR(30),
        allocated_storage INTEGER,
        endpoint VARCHAR(255),
        port INTEGER,
        creation_time TIMESTAMP,
        region VARCHAR(30),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS iam_users (
        id SERIAL PRIMARY KEY,
        user_name VARCHAR(100) NOT NULL,
        user_id VARCHAR(100) NOT NULL,
        arn VARCHAR(255),
        create_date TIMESTAMP,
        password_last_used TIMESTAMP,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
