apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - port: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-writer
spec:
  selector:
    statefulset.kubernetes.io/pod-name: postgres-0
  ports:
    - port: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-readers
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
